title: Celeste(Hangyu) Lv's Homepage
page-top-title: Celeste(Hangyu) Lv
top-section-bg-text: Embodied world models, system-first.
home-subtitle: Celeste(Hangyu) Lv's Homepage
copyright-text: '&copy; Celeste(Hangyu) Lv 2023-2026. All Rights Reserved.'
