title: Celeste(Hangyu) lv's Homepage
page-top-title: Celeste(Hangyu) lv
top-section-bg-text: Embodied world models, system-first.
home-subtitle: Celeste(Hangyu) lv's Homepage
copyright-text: '&copy; Celeste(Hangyu) lv 2023-2026. All Rights Reserved.'
